# Generated by Django 5.1.6 on 2025-03-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='call',
            name='installments',
        ),
        migrations.RemoveField(
            model_name='call',
            name='number_of_months',
        ),
        migrations.RemoveField(
            model_name='call',
            name='start_month',
        ),
    ]
