# Generated by Django 5.1.6 on 2025-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT', models.TextField(blank=True, null=True)),
                ('ID_Number', models.TextField(blank=True, null=True)),
                ('TITLE', models.TextField(blank=True, null=True)),
                ('FIRST_NAME', models.TextField(blank=True, null=True)),
                ('SURNAME', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ClientList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField()),
                ('id_number', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('direction', models.CharField(max_length=10)),
                ('outcome', models.CharField(max_length=10)),
                ('call_result', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
