# Generated by Django 5.1.6 on 2025-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0002_clientlist_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
