# Generated by Django 5.1.6 on 2025-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0003_remove_clientpayment_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='day_of_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='call',
            name='installments',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='number_of_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='call',
            name='start_month',
            field=models.IntegerField(default=1),
        ),
    ]
