# Generated by Django 5.1.6 on 2025-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0004_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
