# Generated by Django 5.1.6 on 2025-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0005_alter_call_installments_alter_call_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='call',
            table='new_client_list10',
        ),
    ]
