# Generated by Django 5.1.6 on 2025-03-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0006_alter_call_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='call',
            table='futura_call',
        ),
    ]
