# Generated by Django 5.1.6 on 2025-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0006_remove_call_email_call_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
