# Generated by Django 5.1.6 on 2025-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0007_alter_call_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='traceresult',
            table='trace_result',
        ),
    ]
