# Generated by Django 5.1.6 on 2025-04-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futura', '0008_alter_traceresult_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientpayment',
            table='client_payments',
        ),
    ]
